### ISSUE TITLE
useragent returns correct values, but they don't work in conditional statements

### ISSUE THREAD

**Issue by fitzage** [lesaff/statamic-useragent#5]
`{{ useragent:is_mobile }}` and `{{ useragent:is_desktop }}` return true/false correctly.

However, I can't seem to find a way to use these in conditional statements. `{{ if useragent:is_desktop }}` does not work as expected.

**Comment by rrelmy** [comment]
Antlers has a different way to use tags inside if conditions, check [Conditions on Tags vs Variables](https://docs.statamic.com/antlers#conditional-logic)

So it would be
``` twig
{{ if { useragent:is_mobile } }}
```
